config/routes.rb
# require 'rails_helper'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauthable: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks'
  }
  root to: "home#index"
  
  resources :wikis
  resources :users
  resources :collaborators, only: [:create, :destroy]
  post 'users/downgrade/:id' => 'users#downgrade', as: :downgrade
  resources :charges, only: [:new, :create]
end

app/models/wiki.rb
# Wiki Model
class Wiki < ApplicationRecord
  belongs_to :user
    validates :title, length: { minimum: 1 }, presence: true
    validates :body, length: { minimum: 100 }, presence: true
    validates :user, presence: true
  has_many :collaborators
  has_many :users, through: :collaborators
end

app/controllers/wikis_controller.rb
# Wikis Controller
class WikisController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index    
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @user = @wiki.user
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was an error saving the Wiki. Please try again."
      render :new  
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki
    if @wiki.update(wiki_params)
      redirect_to @wiki
    else
      if @wiki.save
        flash[:notice] = "Wiki was saved."
        redirect_to [@wiki]
      else
        flash.now[:alert] = "There was an error saving the Wiki. Please try again."
        render :new  
      end
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.delete
      redirect_to @wiki
    else
      if @wiki.save
        flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
        redirect_to [@wiki]
      else
        flash.now[:alert] = "There was an error deleting the Wiki."
        render :show  
      end
    end
  end
private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end


end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
    <%= form_for [@wiki] do |f| %>
      <% if @wiki.errors.any? %>
        <div class="alert alert-danger">
          <h4><%= pluralize(@wiki.errors.count, "error") %>.</h4>
          <ul>
            <% @wiki.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_group_tag(@wiki.errors[:title]) do %>
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      <% end %>
      <%= form_group_tag(@wiki.errors[:body]) do %>
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      <% end %>
      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
      <% end %>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
    <% end %>

app/views/wikis/_wiki.html.erb
<li class="media">
  <div class="media-body">
    <h5 class="mt-0 mb-1"><%= link_to wiki.title, wiki_path(wiki) %></h5>
    <small>Last updated <%= time_ago_in_words(wiki.updated_at) %> ago</small>
  </div>
</li>

app/views/wikis/edit.html.erb
Edit <%= @wiki.title %>
<%= render partial: 'form', locals: { wiki: @wiki } %>

app/views/wikis/index.html.erb
<div class="row">
    <div class="col-md-8">
        <ul class="list-unstyled">
            <%= render partial: 'wiki', collection: @wikis %>
        </ul>
    </div>
    <div class="col-md-4">
        <%= link_to "Create Wiki", new_wiki_path(@wiki), class: 'btn btn-success' %>
    </div>
<div>

app/views/wikis/new.html.erb
 <h1>New Wiki</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for new Wikis</p>
   </div>
   <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
   </div>
 </div>
   </div>
 </div>