config/routes.rb
# require 'rails_helper'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    omniauthable: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks'
  }
  root to: "home#index"
  
  resources :wikis
  resources :users
  resources :collaborators, only: [:create, :destroy]
  post 'users/downgrade/:id' => 'users#downgrade', as: :downgrade
  resources :charges, only: [:new, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <nav class="nav navbar-expand-lg navbar-light bg-light">
        <%= link_to 'Blocipedia', root_path, :class => 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'Wikis', wikis_path, :class => 'nav-link' %>
            </li>
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My Account', user_path(current_user.id), :class => 'nav-link' %>
            </li>
            <% end %>
          </ul>
        </div>
        <div class="navbar-nav nav-item pull-right">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'nav-link d-inline'  %> <%= link_to "Sign In", new_user_session_path, :class => 'nav-link d-inline'  %>
        <% end %>
        </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <p class="error"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <nav class="nav navbar-expand-lg navbar-light bg-light">
        <%= link_to 'Blocipedia', root_path, :class => 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'Wikis', wikis_path, :class => 'nav-link' %>
            </li>
          </ul>
        </div>
        <div class="navbar-nav nav-item pull-right">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'nav-link d-inline'  %> <%= link_to "Sign In", new_user_session_path, :class => 'nav-link d-inline'  %>
        <% end %>
        </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>